import LOGIN from "./Login";
import NoPageFound from "./NoPageFound";
import CORPORATE_AND_INDIVIDUAL_PAGES from "./CorporateAndIndividual";
import ADMIN_PAGES from "./Admin";

const WEB_PAGES = {
  // AUTH PAGES
  LOGIN,

  // CORPORRATE & INDIVIDUAL PAGES
  CORPORATE_AND_INDIVIDUAL_DASHBOARD: CORPORATE_AND_INDIVIDUAL_PAGES.DASHBOARD,
  CORPORATE_AND_INDIVIDUAL_PROJECTS: CORPORATE_AND_INDIVIDUAL_PAGES.PROJECTS,
  CORPORATE_AND_INDIVIDUAL_USER_MANAGEMENT: CORPORATE_AND_INDIVIDUAL_PAGES.USER_MANAGEMENT,


  // ADMIN PAGES

  ADMIN_DASHBOARD: ADMIN_PAGES.DASHBOARD,
  ADMIN_ACTIVITY_LOG: ADMIN_PAGES.ACTIVITY_LOG,
  ADMIN_REPORTS: ADMIN_PAGES.REPORTS,
  ADMIN_PARAMETERS: ADMIN_PAGES.PARAMETERS,
  NO_PAGE_FOUND: NoPageFound,
};
export default WEB_PAGES;
